version: '2.2'

services:
  puppetdb-postgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ./puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    build:
     context: .
     args:
      # replace DOMAINNAME with your Domain
      PUPPETSERVER_FQDN: PUPPETFQDNTOREPLACE
    hostname: puppetdb
    ports:
      - "8080:8080"
      - "8081:8081"
    # Use the below only in case of testing and need to overwrite the FQDN  
    extra_hosts:
      - "PUPPETFQDNTOREPLACE:1.1.1.2"
    volumes:
      - /etc/puppetlabs/puppet/ssl:/etc/puppetlabs/puppet/ssl/

  puppetboard:
    image: puppet/puppetboard
    ports:
      - "8000:8000"

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - "80:80"
    read_only: true
